/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Petrinet;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.border.Border;

/**
 *
 * @author dogboy
 */
public class Item2 extends javax.swing.JFrame {

    /**
     * Creates new form Patient
     */
    public Item2() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_transition.setBorder(label_border);
        jLabel_transition.setForeground(Color.white);
        jLabel_transition1.setBorder(label_border);
        jLabel_transition1.setForeground(Color.white);
        this.setTitle("Item 2 - Patient");
    }
    public static int wt = 0, id = 0, id1 = 0, dn = 0; 
    private Auto_Fire t;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_transition1 = new javax.swing.JLabel();
        jLabel_transition = new javax.swing.JLabel();
        wait_text = new javax.swing.JTextField();
        Name1 = new javax.swing.JLabel();
        inside_text = new javax.swing.JTextField();
        Name2 = new javax.swing.JLabel();
        Name3 = new javax.swing.JLabel();
        done_text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        marking = new javax.swing.JTextField();
        firing = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new RoundedPanel(90, Color.WHITE);
        Wait = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(90, Color.WHITE);
        Inside = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel(90, Color.WHITE);
        Done = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(730, 360));
        getContentPane().setLayout(null);

        jLabel_transition1.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel_transition1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(27, 34, 45))); // NOI18N
        jLabel_transition1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_transition1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_transition1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_transition1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_transition1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel_transition1);
        jLabel_transition1.setBounds(481, 60, 61, 53);

        jLabel_transition.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel_transition.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(27, 34, 45))); // NOI18N
        jLabel_transition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_transition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_transitionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_transitionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_transitionMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_transition);
        jLabel_transition.setBounds(189, 60, 61, 53);

        wait_text.setFont(new java.awt.Font("Hack Nerd Font", 3, 14)); // NOI18N
        wait_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wait_text.setText("0");
        wait_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wait_textKeyTyped(evt);
            }
        });
        getContentPane().add(wait_text);
        wait_text.setBounds(140, 200, 82, 25);

        Name1.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        Name1.setText("Wait");
        getContentPane().add(Name1);
        Name1.setBounds(100, 200, 38, 20);

        inside_text.setFont(new java.awt.Font("Hack Nerd Font", 3, 14)); // NOI18N
        inside_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inside_text.setText("0");
        inside_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inside_textKeyTyped(evt);
            }
        });
        getContentPane().add(inside_text);
        inside_text.setBounds(340, 200, 82, 25);

        Name2.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        Name2.setText("Inside");
        getContentPane().add(Name2);
        Name2.setBounds(280, 200, 52, 20);

        Name3.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        Name3.setText("Done");
        getContentPane().add(Name3);
        Name3.setBounds(500, 200, 45, 20);

        done_text.setFont(new java.awt.Font("Hack Nerd Font", 3, 14)); // NOI18N
        done_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        done_text.setText("0");
        done_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                done_textActionPerformed(evt);
            }
        });
        done_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                done_textKeyTyped(evt);
            }
        });
        getContentPane().add(done_text);
        done_text.setBounds(550, 200, 82, 25);

        jButton1.setFont(new java.awt.Font("Hack Nerd Font", 1, 18)); // NOI18N
        jButton1.setText("Set token");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 240, 115, 33);

        jLabel4.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel4.setText("Start");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 20, 41, 28);

        jLabel5.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel5.setText("Change");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(480, 20, 66, 31);

        jLabel6.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel6.setText("------->");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(118, 60, 53, 53);

        jLabel7.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel7.setText("------->");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 68, 61, 45);

        jLabel8.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel8.setText("------->");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(418, 78, 62, 24);

        jLabel9.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel9.setText("------->");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(560, 76, 53, 24);

        jLabel10.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel10.setText("Firing");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 140, 50, 46);

        jLabel11.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel11.setText("Marking");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(350, 140, 69, 46);

        marking.setFont(new java.awt.Font("Hack Nerd Font", 3, 14)); // NOI18N
        marking.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        marking.setText("[0.Wait,0.Inside,0.Done]");
        getContentPane().add(marking);
        marking.setBounds(430, 150, 200, 25);

        firing.setFont(new java.awt.Font("Hack Nerd Font", 3, 14)); // NOI18N
        firing.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(firing);
        firing.setBounds(200, 150, 78, 25);

        jLabel12.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel12.setText("Wait");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 20, 55, 24);

        jLabel13.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel13.setText("Inside");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 20, 52, 24);

        jLabel14.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel14.setText("Done");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(640, 20, 45, 24);

        jToggleButton1.setBackground(new java.awt.Color(44, 218, 92));
        jToggleButton1.setFont(new java.awt.Font("Hack Nerd Font", 1, 18)); // NOI18N
        jToggleButton1.setText("ON");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(330, 240, 106, 33);

        jLabel15.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel15.setText("Auto Fire");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(340, 280, 79, 24);

        jButton2.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 240, 96, 33);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        Wait.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(Wait, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Wait, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(32, 53, 76, 73);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        Inside.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(Inside, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inside, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(331, 53, 77, 73);

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        Done.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(Done, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Done, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(625, 53, 75, 73);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_transition1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_transition1MouseClicked
        
        dn = Integer.parseInt(Done.getText());
        id = Integer.parseInt(Inside.getText());
        
        if (id > 0) {
            id -= 1;
            dn += 1;
        
        
            Done.setText(String.valueOf(dn));
            Inside.setText(String.valueOf(id));
        
            firing.setText("Change");
        }
        Marking();
    }//GEN-LAST:event_jLabel_transition1MouseClicked

    private void jLabel_transition1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_transition1MouseEntered
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.yellow);
        jLabel_transition1.setBorder(label_border);
        jLabel_transition1.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel_transition1MouseEntered

    private void jLabel_transition1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_transition1MouseExited
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_transition1.setBorder(label_border);
        jLabel_transition1.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_transition1MouseExited

    private void jLabel_transitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_transitionMouseClicked
        
        wt = Integer.parseInt(Wait.getText());
        id = Integer.parseInt(Inside.getText());
        
        if (wt > 0) {
            wt -= 1;
            id += 1;
    
        
        Wait.setText(String.valueOf(wt));
        Inside.setText(String.valueOf(id));
        
        firing.setText("Start");
    }
        Marking();
        
    }//GEN-LAST:event_jLabel_transitionMouseClicked

    private void jLabel_transitionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_transitionMouseEntered
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.yellow);
        jLabel_transition.setBorder(label_border);
        jLabel_transition.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel_transitionMouseEntered

    private void jLabel_transitionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_transitionMouseExited
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_transition.setBorder(label_border);
        jLabel_transition.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_transitionMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (t != null) {
            
            t.cancel(true);
            t = null;
            jButton1.setEnabled(true);
        }
        if (!(wait_text.getText().equals("")) && (Integer.parseInt(wait_text.getText())>10))
        {
            JOptionPane.showMessageDialog(this,"The number of token in wait is not greater than 10","Warning",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(wait_text.getText().equals("")) wt = 0;
        else wt = Integer.parseInt(wait_text.getText());
        
        if(inside_text.getText().equals("")) id = 0;
        else id = Integer.parseInt(inside_text.getText());

        if(done_text.getText().equals("")) dn = 0;
        else dn = Integer.parseInt(done_text.getText());
        
        if (wt >= 0 && id >= 0 && dn >= 0) {
            
            Wait.setText(String.valueOf(wt));
            Inside.setText(String.valueOf(id));
            Done.setText(String.valueOf(dn));
            if (wt == 0 && id == 0 && dn == 0) jButton1.setEnabled(true);
            else jButton1.setEnabled(false);
            
            if (jToggleButton1.getText().equals("OFF")) {
                
                jToggleButton1.doClick();
                jToggleButton1.setBackground(Color.green);
            }
        }
        
        Marking();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
        if (jToggleButton1.isSelected()) {
            
            jToggleButton1.setText("OFF");
            jToggleButton1.setBackground(Color.red);
            
            jButton1.setEnabled(true);
            
            (t = new Auto_Fire()).execute();
             
        }
        else {
            
            jToggleButton1.setText("ON");
            jToggleButton1.setBackground(Color.green);
            
            if (t != null) {
            
                t.cancel(true);
                t = null;
                jButton1.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void done_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_done_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_done_textActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Wait.setText("0");
        Inside.setText("0");
        Done.setText("0");
        firing.setText("");
        Marking();
        wait_text.setText("0");
        inside_text.setText("0");
        done_text.setText("0");
        
        if (jToggleButton1.getText().equals("OFF")) {
                
                jToggleButton1.doClick();
                jToggleButton1.setText("ON");
                jToggleButton1.setBackground(Color.green);
            }
        
        if (t != null) {
            
            t.cancel(true);
            t = null;
            
        }
        jButton2.setEnabled(true);
        jButton1.setEnabled(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void wait_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wait_textKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_wait_textKeyTyped

    private void inside_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inside_textKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_inside_textKeyTyped

    private void done_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_done_textKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_done_textKeyTyped
    
    public void Marking() {
        
        String w = Wait.getText(), i = Inside.getText(), d = Done.getText();
        marking.setText("[" + w + ".Wait," + i + ".Inside," + d + ".Done]");
    }
    
    private class Auto_Fire extends SwingWorker<Void, String> {
        
        @Override
        protected Void doInBackground() throws InterruptedException {
            
            wt = Integer.parseInt(Wait.getText());
            id = Integer.parseInt(Inside.getText());
            dn = Integer.parseInt(Done.getText());
            boolean found = false;
            
            while(!isCancelled() && !found) {
                
                
                while (wt > 0) {   
                    firing.setText("Start");
                    wt -= 1;
                    Wait.setText(String.valueOf(wt));
                    
                    id++;
                    Inside.setText(String.valueOf(id));
                    
                    Marking();
                    Thread.sleep(1000);
                    
                    
                }
                
                while (id > 0) {
                    firing.setText("Change");
                    id -= 1;
                    Inside.setText(String.valueOf(id));
                    
                    dn += 1;
                    Done.setText(String.valueOf(dn));
                    
                    Marking();
                    Thread.sleep(1000);
                }
                
                jButton1.setEnabled(true);
                
                found = true;
            }
            return null;
        }
        
        @Override
        protected void done() {}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Item2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Item2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Item2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Item2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Item2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Done;
    private javax.swing.JLabel Inside;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Wait;
    private javax.swing.JTextField done_text;
    private javax.swing.JTextField firing;
    private javax.swing.JTextField inside_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_transition;
    private javax.swing.JLabel jLabel_transition1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField marking;
    private javax.swing.JTextField wait_text;
    // End of variables declaration//GEN-END:variables

}
