/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Petrinet;

import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Minh Thuc
 */
public class Item3_4 extends javax.swing.JFrame {

    int free,busy,docu,wait,inside,done;
    Auto t;
    public Item3_4() {
        initComponents();
        this.setLocationRelativeTo(null);
        free=0;
        busy=0;
        docu=0;
        wait=0;
        inside=0;
        done=0;
        Place1.setText(String.valueOf(wait));
        Place2.setText(String.valueOf(free));
        Place3.setText(String.valueOf(inside));
        Place4.setText(String.valueOf(busy));
        Place5.setText(String.valueOf(done));
        Place6.setText(String.valueOf(docu));
        text7.setText("");
        String s = "[" + String.valueOf(wait) + ".wait,"+ String.valueOf(free) + ".free,"+ String.valueOf(inside) + ".inside,"+ String.valueOf(busy) + ".busy,"+ String.valueOf(done) + ".done,"+ String.valueOf(docu) + ".docu]";
        text8.setText(s);
        t=null;
        this.setTitle("Item 3_4 - Superimposed");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Place1 = new javax.swing.JLabel();
        Place2 = new javax.swing.JLabel();
        Place3 = new javax.swing.JLabel();
        Place4 = new javax.swing.JLabel();
        Place5 = new javax.swing.JLabel();
        Place6 = new javax.swing.JLabel();
        Docu = new javax.swing.JLabel();
        Start = new javax.swing.JLabel();
        End = new javax.swing.JLabel();
        Free = new javax.swing.JLabel();
        Busy = new javax.swing.JLabel();
        Change = new javax.swing.JLabel();
        Wait = new javax.swing.JLabel();
        Inside = new javax.swing.JLabel();
        Done = new javax.swing.JLabel();
        tt1 = new javax.swing.JLabel();
        tt2 = new javax.swing.JLabel();
        tt3 = new javax.swing.JLabel();
        tt4 = new javax.swing.JLabel();
        tt5 = new javax.swing.JLabel();
        tt6 = new javax.swing.JLabel();
        tt7 = new javax.swing.JLabel();
        tt9 = new javax.swing.JLabel();
        tt8 = new javax.swing.JLabel();
        tt10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        wait_text = new javax.swing.JTextField();
        Name1 = new javax.swing.JLabel();
        free_text = new javax.swing.JTextField();
        Name2 = new javax.swing.JLabel();
        inside_text = new javax.swing.JTextField();
        Name3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        busy_text = new javax.swing.JTextField();
        Name4 = new javax.swing.JLabel();
        done_text = new javax.swing.JTextField();
        Name5 = new javax.swing.JLabel();
        docu_text = new javax.swing.JTextField();
        Name6 = new javax.swing.JLabel();
        text7 = new javax.swing.JTextField();
        Name7 = new javax.swing.JLabel();
        text8 = new javax.swing.JTextField();
        Name8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(780, 500));
        getContentPane().setLayout(null);

        Place1.setText(" ");
        getContentPane().add(Place1);
        Place1.setBounds(50, 180, 30, 14);

        Place2.setText(" ");
        getContentPane().add(Place2);
        Place2.setBounds(200, 40, 30, 14);

        Place3.setText(" ");
        getContentPane().add(Place3);
        Place3.setBounds(350, 290, 30, 14);

        Place4.setText(" ");
        getContentPane().add(Place4);
        Place4.setBounds(350, 180, 30, 14);

        Place5.setText(" ");
        getContentPane().add(Place5);
        Place5.setBounds(650, 180, 30, 14);

        Place6.setText(" ");
        getContentPane().add(Place6);
        Place6.setBounds(500, 40, 30, 14);

        Docu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Docu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/place.png"))); // NOI18N
        Docu.setText("Docu");
        Docu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Docu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Docu.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(Docu);
        Docu.setBounds(480, 0, 79, 80);

        Start.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/transition.png"))); // NOI18N
        Start.setText("Start");
        Start.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Start.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Start.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartMouseClicked(evt);
            }
        });
        getContentPane().add(Start);
        Start.setBounds(180, 150, 100, 80);

        End.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        End.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/transition.png"))); // NOI18N
        End.setText("End");
        End.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        End.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        End.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        End.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EndMouseClicked(evt);
            }
        });
        getContentPane().add(End);
        End.setBounds(330, 0, 73, 80);

        Free.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Free.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/place.png"))); // NOI18N
        Free.setText("Free");
        Free.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Free.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Free.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(Free);
        Free.setBounds(180, 0, 77, 80);
        ;

        Busy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Busy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/place.png"))); // NOI18N
        Busy.setText("Busy");
        Busy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Busy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Busy.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(Busy);
        Busy.setBounds(330, 140, 80, 80);

        Change.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Change.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/transition.png"))); // NOI18N
        Change.setText("Change");
        Change.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Change.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Change.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Change.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeMouseClicked(evt);
            }
        });
        getContentPane().add(Change);
        Change.setBounds(480, 150, 120, 80);

        Wait.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Wait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/place.png"))); // NOI18N
        Wait.setText("Wait");
        Wait.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Wait.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Wait.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(Wait);
        Wait.setBounds(30, 140, 77, 80);
        ;

        Inside.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Inside.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/place.png"))); // NOI18N
        Inside.setText("Inside");
        Inside.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Inside.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Inside.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(Inside);
        Inside.setBounds(330, 250, 90, 80);
        ;

        Done.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/place.png"))); // NOI18N
        Done.setText("Done");
        Done.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Done.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Done.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(Done);
        Done.setBounds(630, 140, 90, 80);
        ;

        tt1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/Item3_TT.png"))); // NOI18N
        tt1.setAutoscrolls(true);
        tt1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tt1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tt1.setVerifyInputWhenFocusTarget(false);
        tt1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(tt1);
        tt1.setBounds(380, 180, 100, 20);

        tt2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/Item3_TT1.png"))); // NOI18N
        tt2.setAutoscrolls(true);
        tt2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tt2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tt2.setVerifyInputWhenFocusTarget(false);
        tt2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(tt2);
        tt2.setBounds(230, 40, 140, 20);

        tt3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/Item3_TT3.png"))); // NOI18N
        tt3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tt3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tt3.setVerifyInputWhenFocusTarget(false);
        tt3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(tt3);
        tt3.setBounds(490, 70, 30, 100);

        tt4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/Item3_TT.png"))); // NOI18N
        tt4.setAutoscrolls(true);
        tt4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tt4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tt4.setVerifyInputWhenFocusTarget(false);
        tt4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(tt4);
        tt4.setBounds(530, 180, 100, 20);

        tt5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tt5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/Item3_TT.png"))); // NOI18N
        tt5.setAutoscrolls(true);
        tt5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tt5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tt5.setVerifyInputWhenFocusTarget(false);
        tt5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(tt5);
        tt5.setBounds(80, 180, 100, 20);

        tt6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tt6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/Item3_TT2.png"))); // NOI18N
        tt6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tt6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tt6.setVerifyInputWhenFocusTarget(false);
        tt6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(tt6);
        tt6.setBounds(190, 70, 30, 100);

        tt7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tt7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/Item3_TT5.png"))); // NOI18N
        tt7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tt7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tt7.setVerifyInputWhenFocusTarget(false);
        tt7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(tt7);
        tt7.setBounds(390, 210, 140, 100);

        tt9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tt9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/Item3_TT1.png"))); // NOI18N
        tt9.setAutoscrolls(true);
        tt9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tt9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tt9.setVerifyInputWhenFocusTarget(false);
        tt9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(tt9);
        tt9.setBounds(380, 40, 140, 20);

        tt8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tt8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/Item3_TT4.png"))); // NOI18N
        tt8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tt8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tt8.setVerifyInputWhenFocusTarget(false);
        tt8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(tt8);
        tt8.setBounds(200, 210, 140, 100);

        tt10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tt10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Petrinet/Item3_TT.png"))); // NOI18N
        tt10.setAutoscrolls(true);
        tt10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tt10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tt10.setVerifyInputWhenFocusTarget(false);
        tt10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(tt10);
        tt10.setBounds(230, 180, 100, 20);

        jButton1.setText("Set token");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 420, 90, 23);

        jButton2.setText("Auto Fire");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 420, 90, 23);

        wait_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wait_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wait_textKeyTyped(evt);
            }
        });
        getContentPane().add(wait_text);
        wait_text.setBounds(70, 380, 60, 20);

        Name1.setText("Wait");
        getContentPane().add(Name1);
        Name1.setBounds(40, 380, 40, 20);

        free_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        free_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                free_textKeyTyped(evt);
            }
        });
        getContentPane().add(free_text);
        free_text.setBounds(180, 380, 60, 20);

        Name2.setText("Free");
        getContentPane().add(Name2);
        Name2.setBounds(150, 380, 40, 20);

        inside_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inside_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inside_textKeyTyped(evt);
            }
        });
        getContentPane().add(inside_text);
        inside_text.setBounds(300, 380, 60, 20);

        Name3.setText("Inside");
        getContentPane().add(Name3);
        Name3.setBounds(260, 380, 50, 20);

        jButton3.setText("Stop Auto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 420, 90, 23);

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(540, 420, 90, 23);

        busy_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        busy_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busy_textKeyTyped(evt);
            }
        });
        getContentPane().add(busy_text);
        busy_text.setBounds(410, 380, 60, 20);

        Name4.setText("Busy");
        getContentPane().add(Name4);
        Name4.setBounds(380, 380, 40, 20);

        done_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        done_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                done_textKeyTyped(evt);
            }
        });
        getContentPane().add(done_text);
        done_text.setBounds(530, 380, 60, 20);

        Name5.setText("Done");
        getContentPane().add(Name5);
        Name5.setBounds(500, 380, 40, 20);

        docu_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        docu_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                docu_textKeyTyped(evt);
            }
        });
        getContentPane().add(docu_text);
        docu_text.setBounds(650, 380, 60, 20);

        Name6.setText("Docu");
        getContentPane().add(Name6);
        Name6.setBounds(620, 380, 40, 20);

        text7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(text7);
        text7.setBounds(150, 340, 60, 20);

        Name7.setText("Firing");
        getContentPane().add(Name7);
        Name7.setBounds(110, 340, 40, 20);

        text8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(text8);
        text8.setBounds(290, 340, 330, 20);

        Name8.setText("Marking");
        getContentPane().add(Name8);
        Name8.setBounds(240, 340, 50, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartMouseClicked
        // TODO add your handling code here:
        if ((free>0) && (wait>0))
        {
            free--;
            wait--;
            busy++;
            inside++;
            Place1.setText(String.valueOf(wait));
            Place2.setText(String.valueOf(free));
            Place3.setText(String.valueOf(inside));
            Place4.setText(String.valueOf(busy));
            text7.setText("start");
            String s = "[" + String.valueOf(wait) + ".wait,"+ String.valueOf(free) + ".free,"+ String.valueOf(inside) + ".inside,"+ String.valueOf(busy) + ".busy,"+ String.valueOf(done) + ".done,"+ String.valueOf(docu) + ".docu]";
            text8.setText(s);
        }
    }//GEN-LAST:event_StartMouseClicked

    private void EndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EndMouseClicked
        // TODO add your handling code here:
        if (docu>0)
        {
            docu--;
            free++;
            Place2.setText(String.valueOf(free));
            Place6.setText(String.valueOf(docu));
            text7.setText("end");
            String s = "[" + String.valueOf(wait) + ".wait,"+ String.valueOf(free) + ".free,"+ String.valueOf(inside) + ".inside,"+ String.valueOf(busy) + ".busy,"+ String.valueOf(done) + ".done,"+ String.valueOf(docu) + ".docu]";
            text8.setText(s);
        }
    }//GEN-LAST:event_EndMouseClicked

    private void ChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeMouseClicked
        // TODO add your handling code here:
        if ((busy>0) && (inside>0))
        {
            busy--;
            inside--;
            docu++;
            done++;
            Place3.setText(String.valueOf(inside));
            Place4.setText(String.valueOf(busy));
            Place5.setText(String.valueOf(done));
            Place6.setText(String.valueOf(docu));
            text7.setText("change");
            String s = "[" + String.valueOf(wait) + ".wait,"+ String.valueOf(free) + ".free,"+ String.valueOf(inside) + ".inside,"+ String.valueOf(busy) + ".busy,"+ String.valueOf(done) + ".done,"+ String.valueOf(docu) + ".docu]";
            text8.setText(s);
        }
    }//GEN-LAST:event_ChangeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!(wait_text.getText().equals("")) && (Integer.parseInt(wait_text.getText())>10))
        {
            JOptionPane.showMessageDialog(this,"The number of token in wait is not greater than 10","Warning",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(busy_text.getText().equals("")) busy = 0;
        else busy = Integer.parseInt(busy_text.getText());

        if(free_text.getText().equals("")) free = 0;
        else free = Integer.parseInt(free_text.getText());
        
        if(docu_text.getText().equals("")) docu = 0;
        else docu = Integer.parseInt(docu_text.getText()); 
        
        if(wait_text.getText().equals("")) wait = 0;
        else wait = Integer.parseInt(wait_text.getText());
        
        if(inside_text.getText().equals("")) inside = 0;
        else inside = Integer.parseInt(inside_text.getText());

        if(done_text.getText().equals("")) done = 0;
        else done = Integer.parseInt(done_text.getText());
        
        Place1.setText(String.valueOf(wait));
        Place2.setText(String.valueOf(free));
        Place3.setText(String.valueOf(inside));
        Place4.setText(String.valueOf(busy));
        Place5.setText(String.valueOf(done));
        Place6.setText(String.valueOf(docu));
        text7.setText("");
        String s = "[" + String.valueOf(wait) + ".wait,"+ String.valueOf(free) + ".free,"+ String.valueOf(inside) + ".inside,"+ String.valueOf(busy) + ".busy,"+ String.valueOf(done) + ".done,"+ String.valueOf(docu) + ".docu]";
        text8.setText(s);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        (t=new Auto()).execute();
        jButton2.setEnabled(false);
        jButton3.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (t!=null)
        {
            t.cancel(true);
            t=null;
            jButton2.setEnabled(true);
            jButton3.setEnabled(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        free=0;
        busy=0;
        docu=0;
        wait=0;
        inside=0;
        done=0;
        Place1.setText(String.valueOf(wait));
        Place4.setText(String.valueOf(busy));
        Place6.setText(String.valueOf(docu));
        Place5.setText(String.valueOf(done));
        Place3.setText(String.valueOf(inside));
        Place2.setText(String.valueOf(free));
        text7.setText("");
        String s = "[" + String.valueOf(wait) + ".wait,"+ String.valueOf(free) + ".free,"+ String.valueOf(inside) + ".inside,"+ String.valueOf(busy) + ".busy,"+ String.valueOf(done) + ".done,"+ String.valueOf(docu) + ".docu]";
        text8.setText(s);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void wait_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wait_textKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_wait_textKeyTyped

    private void free_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_free_textKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_free_textKeyTyped

    private void inside_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inside_textKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_inside_textKeyTyped

    private void busy_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busy_textKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_busy_textKeyTyped

    private void done_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_done_textKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_done_textKeyTyped

    private void docu_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_docu_textKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_docu_textKeyTyped
    
    private class Auto extends SwingWorker<Void, String>
    {

        @Override
        protected Void doInBackground() throws Exception {
            while (!isCancelled())
            {
                while ((busy>0) && (inside>0))
                {
                    busy--;
                    inside--;
                    docu++;
                    done++;
                    Place3.setText(String.valueOf(inside));
                    Place4.setText(String.valueOf(busy));
                    Place5.setText(String.valueOf(done));
                    Place6.setText(String.valueOf(docu));
                    text7.setText("change");
                    String s = "[" + String.valueOf(wait) + ".wait,"+ String.valueOf(free) + ".free,"+ String.valueOf(inside) + ".inside,"+ String.valueOf(busy) + ".busy,"+ String.valueOf(done) + ".done,"+ String.valueOf(docu) + ".docu]";
                    text8.setText(s);
                    Thread.sleep(1000);
                }
                while (docu>0)
                {
                    docu--;
                    free++;
                    Place2.setText(String.valueOf(free));
                    Place6.setText(String.valueOf(docu));
                    text7.setText("end");
                    String s = "[" + String.valueOf(wait) + ".wait,"+ String.valueOf(free) + ".free,"+ String.valueOf(inside) + ".inside,"+ String.valueOf(busy) + ".busy,"+ String.valueOf(done) + ".done,"+ String.valueOf(docu) + ".docu]";
                    text8.setText(s);
                    Thread.sleep(1000);
                }
                while ((free>0) && (wait>0))
                {
                    free--;
                    wait--;
                    busy++;
                    inside++;
                    Place1.setText(String.valueOf(wait));
                    Place2.setText(String.valueOf(free));
                    Place3.setText(String.valueOf(inside));
                    Place4.setText(String.valueOf(busy));
                    text7.setText("start");
                    String s = "[" + String.valueOf(wait) + ".wait,"+ String.valueOf(free) + ".free,"+ String.valueOf(inside) + ".inside,"+ String.valueOf(busy) + ".busy,"+ String.valueOf(done) + ".done,"+ String.valueOf(docu) + ".docu]";
                    text8.setText(s);
                    Thread.sleep(1000);
                }
            }
            Thread.sleep(1000);
            return null;
        }
            
        @Override
        protected void done()
        {
            
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Item3_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Item3_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Item3_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Item3_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Item3_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Busy;
    private javax.swing.JLabel Change;
    private javax.swing.JLabel Docu;
    private javax.swing.JLabel Done;
    private javax.swing.JLabel End;
    private javax.swing.JLabel Free;
    private javax.swing.JLabel Inside;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Name4;
    private javax.swing.JLabel Name5;
    private javax.swing.JLabel Name6;
    private javax.swing.JLabel Name7;
    private javax.swing.JLabel Name8;
    private javax.swing.JLabel Place1;
    private javax.swing.JLabel Place2;
    private javax.swing.JLabel Place3;
    private javax.swing.JLabel Place4;
    private javax.swing.JLabel Place5;
    private javax.swing.JLabel Place6;
    private javax.swing.JLabel Start;
    private javax.swing.JLabel Wait;
    private javax.swing.JTextField busy_text;
    private javax.swing.JTextField docu_text;
    private javax.swing.JTextField done_text;
    private javax.swing.JTextField free_text;
    private javax.swing.JTextField inside_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField text7;
    private javax.swing.JTextField text8;
    private javax.swing.JLabel tt1;
    private javax.swing.JLabel tt10;
    private javax.swing.JLabel tt2;
    private javax.swing.JLabel tt3;
    private javax.swing.JLabel tt4;
    private javax.swing.JLabel tt5;
    private javax.swing.JLabel tt6;
    private javax.swing.JLabel tt7;
    private javax.swing.JLabel tt8;
    private javax.swing.JLabel tt9;
    private javax.swing.JTextField wait_text;
    // End of variables declaration//GEN-END:variables
}
